### ISSUE TITLE
Setting tsim = 100.0 causes crash in main-loop branch

### ISSUE THREAD

**Issue by drwebb** [sheiksadique/HSimSNN#4]
Something is causing an array out of bounds index error when tsim is set to 100.0. This seems be caused by the [conditional being removed and instead using `mergeST` ](https://github.com/sheiksadique/HSimSNN/commit/91cd212ae4c03d7a01da67c7a47a85e8e34f8436)

**Comment by sheiksadique** [comment]
I fixed the mergeST function to return an EmptySpikeTrian when when it is an EmptySpikeTrain
